[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "ğŸ¤– AI"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "ğŸ¬ å…¨çƒåª’ä½“"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "ğŸ“² èŠå¤©è½¯ä»¶"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",".*"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯"
type = "select"
rule = ["[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ è‹¹æœ"
type = "select"
rule = ["[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ¯ ç›´æ¥è¿æ¥"
type = "select"
rule = ["[]DIRECT","[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆä¸‹è½½"
type = "select"
rule = ["[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ® æ¸¸æˆå¹³å°"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",".*"]

[[custom_groups]]
name = "ğŸ“º å“”å“©å“”å“©"
type = "select"
rule = ["[]ğŸ¯ ç›´æ¥è¿æ¥",".*"]

[[custom_groups]]
name = "ğŸ“º å·´å“ˆå§†ç‰¹"
type = "select"
rule = ["(å°|tw)"]

[[custom_groups]]
name = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©"]