[[rulesets]]
group = "ğŸ›‘ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/Block.list"

[[rulesets]]
group = "ğŸ¤– AI"
ruleset = "rules/AI.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆä¸‹è½½"
ruleset = "rules/GamesDownload.list"

[[rulesets]]
group = "ğŸ® æ¸¸æˆå¹³å°"
ruleset = "rules/Games.list"

[[rulesets]]
group = "ğŸ“² èŠå¤©è½¯ä»¶"
ruleset = "rules/Chat.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "rules/BiliBili.list"

[[rulesets]]
group = "ğŸ“º å·´å“ˆå§†ç‰¹"
ruleset = "rules/Bahamut.list"

[[rulesets]]
group = "ğŸ¬ å…¨çƒåª’ä½“"
ruleset = "rules/JapanMedia.list"

[[rulesets]]
group = "ğŸ¬ å…¨çƒåª’ä½“"
ruleset = "rules/GlobalMedia.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯"
ruleset = "rules/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœ"
ruleset = "rules/Apple.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/NodePick.list"

[[rulesets]]
group = "ğŸ¯ ç›´æ¥è¿æ¥"
ruleset = "rules/DirectConnection.list"

[[rulesets]]
group = "ğŸ¯ ç›´æ¥è¿æ¥"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"